{
 "title": "LibreNMS-11",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "DataBases",
    "query": "show databases like 'school_%';"
   },
   {
    "name": "Devices",
    "query": "select sysName from $DataBases.devices"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT sysName AS Device,\n       status AS Status,\n       (CASE WHEN status = 0 THEN 'N/A' ELSE uptime END) AS Uptime \nFROM $DataBases.devices"
    }
   ]
  },
  {
   "title": "processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  a.timestamp AS \"time\",\n  a.max,\n  a.min\nFROM $DataBases.device_perf a, $DataBases.devices b\nWHERE\n  a.device_id = b.device_id AND\n  b.sysName = '$Devices'\nORDER BY a.timestamp"
    }
   ]
  },
  {
   "title": "Alert Log",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT b.sysName,\n       a.details, a.state,\n       a.time_logged\nFROM $DataBases.alert_log a, $DataBases.devices b\nWHERE a.device_id = b.device_id\nORDER BY a.time_logged DESC"
    }
   ]
  }
 ]
}